version: 0.2

phases:
  pre_build:
    commands:
      dotnet restore MyEmployeeApp/MyEmployeeApp.csproj
  build:
    commands:
      dotnet build MyEmployeeApp/MyEmployeeApp.csproj
      dotnet publish -c release MyEmployeeApp/MyEmployeeApp.csproj -o ./publish
artifacts:
  files:
    - scripts/**/*
    - appspec.yml
    - ./publish/**/*
